# Generated by Django 3.0.4 on 2020-04-24 12:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WLUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='主键')),
                ('nickname', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=1)], verbose_name='昵称')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='邮箱')),
                ('telephone', models.CharField(blank=True, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(regex='1[35678]\\d{9}')], verbose_name='手机号')),
                ('doc', models.CharField(blank=True, max_length=255, verbose_name='个人简介')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('is_staff', models.BooleanField(default=False, verbose_name='是否是管理员')),
                ('time_joined', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('avatar', models.URLField(blank=True, verbose_name='头像')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'wluser',
            },
        ),
        migrations.CreateModel(
            name='WLPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100, unique=True, verbose_name='路由')),
                ('describe', models.SmallIntegerField(choices=[(1, 'read'), (2, 'write'), (3, 'update')], verbose_name='权限描述')),
                ('users', models.ManyToManyField(related_name='permissions', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'wlpermissions',
            },
        ),
        migrations.CreateModel(
            name='WLGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, unique=True, verbose_name='分组名')),
                ('permissions', models.ManyToManyField(related_name='groups', to='wlauth.WLPermissions', verbose_name='关联权限')),
                ('users', models.ManyToManyField(related_name='groups', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
        ),
    ]
