# Generated by Django 3.0.4 on 2020-04-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wluser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='是否为超级管理员'),
        ),
    ]
